// Code generated by MockGen. DO NOT EDIT.
// Source: ../repository/order_repository.go
//
// Generated by this command:
//
//	mockgen -source=../repository/order_repository.go -package=orders -destination=mock_order_repository_test.go -mock_names OrderRepository=MockOrderRepository
//

// Package orders is a generated GoMock package.
package orders

import (
	context "context"
	reflect "reflect"
	time "time"

	repository "github.com/kayumovtd/gophermart/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderRepository is a mock of OrderRepository interface.
type MockOrderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepositoryMockRecorder
	isgomock struct{}
}

// MockOrderRepositoryMockRecorder is the mock recorder for MockOrderRepository.
type MockOrderRepositoryMockRecorder struct {
	mock *MockOrderRepository
}

// NewMockOrderRepository creates a new mock instance.
func NewMockOrderRepository(ctrl *gomock.Controller) *MockOrderRepository {
	mock := &MockOrderRepository{ctrl: ctrl}
	mock.recorder = &MockOrderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepository) EXPECT() *MockOrderRepositoryMockRecorder {
	return m.recorder
}

// ClaimForProcessing mocks base method.
func (m *MockOrderRepository) ClaimForProcessing(ctx context.Context, claim repository.OrderClaim) ([]repository.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimForProcessing", ctx, claim)
	ret0, _ := ret[0].([]repository.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimForProcessing indicates an expected call of ClaimForProcessing.
func (mr *MockOrderRepositoryMockRecorder) ClaimForProcessing(ctx, claim any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimForProcessing", reflect.TypeOf((*MockOrderRepository)(nil).ClaimForProcessing), ctx, claim)
}

// Complete mocks base method.
func (m *MockOrderRepository) Complete(ctx context.Context, orderID int64, completion repository.OrderCompletion) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Complete", ctx, orderID, completion)
	ret0, _ := ret[0].(error)
	return ret0
}

// Complete indicates an expected call of Complete.
func (mr *MockOrderRepositoryMockRecorder) Complete(ctx, orderID, completion any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Complete", reflect.TypeOf((*MockOrderRepository)(nil).Complete), ctx, orderID, completion)
}

// Create mocks base method.
func (m *MockOrderRepository) Create(ctx context.Context, userID int64, number, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userID, number, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOrderRepositoryMockRecorder) Create(ctx, userID, number, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOrderRepository)(nil).Create), ctx, userID, number, status)
}

// GetByNumber mocks base method.
func (m *MockOrderRepository) GetByNumber(ctx context.Context, number string) (repository.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByNumber", ctx, number)
	ret0, _ := ret[0].(repository.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByNumber indicates an expected call of GetByNumber.
func (mr *MockOrderRepositoryMockRecorder) GetByNumber(ctx, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByNumber", reflect.TypeOf((*MockOrderRepository)(nil).GetByNumber), ctx, number)
}

// ListByUserID mocks base method.
func (m *MockOrderRepository) ListByUserID(ctx context.Context, userID int64) ([]repository.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", ctx, userID)
	ret0, _ := ret[0].([]repository.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockOrderRepositoryMockRecorder) ListByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockOrderRepository)(nil).ListByUserID), ctx, userID)
}

// Requeue mocks base method.
func (m *MockOrderRepository) Requeue(ctx context.Context, orderIDs []int64, nextAttemptAt, updatedAt time.Time, lastError *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Requeue", ctx, orderIDs, nextAttemptAt, updatedAt, lastError)
	ret0, _ := ret[0].(error)
	return ret0
}

// Requeue indicates an expected call of Requeue.
func (mr *MockOrderRepositoryMockRecorder) Requeue(ctx, orderIDs, nextAttemptAt, updatedAt, lastError any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Requeue", reflect.TypeOf((*MockOrderRepository)(nil).Requeue), ctx, orderIDs, nextAttemptAt, updatedAt, lastError)
}
