// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/balance_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/balance_repository.go -package=balance -destination=internal/balance/mock_balance_repository_test.go -mock_names BalanceRepository=MockBalanceRepository
//

// Package balance is a generated GoMock package.
package balance

import (
	context "context"
	reflect "reflect"
	time "time"

	repository "github.com/kayumovtd/gophermart/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockBalanceRepository is a mock of BalanceRepository interface.
type MockBalanceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceRepositoryMockRecorder
	isgomock struct{}
}

// MockBalanceRepositoryMockRecorder is the mock recorder for MockBalanceRepository.
type MockBalanceRepositoryMockRecorder struct {
	mock *MockBalanceRepository
}

// NewMockBalanceRepository creates a new mock instance.
func NewMockBalanceRepository(ctrl *gomock.Controller) *MockBalanceRepository {
	mock := &MockBalanceRepository{ctrl: ctrl}
	mock.recorder = &MockBalanceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalanceRepository) EXPECT() *MockBalanceRepositoryMockRecorder {
	return m.recorder
}

// GetBalance mocks base method.
func (m *MockBalanceRepository) GetBalance(ctx context.Context, userID int64) (repository.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, userID)
	ret0, _ := ret[0].(repository.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockBalanceRepositoryMockRecorder) GetBalance(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockBalanceRepository)(nil).GetBalance), ctx, userID)
}

// ListWithdrawals mocks base method.
func (m *MockBalanceRepository) ListWithdrawals(ctx context.Context, userID int64) ([]repository.Withdrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWithdrawals", ctx, userID)
	ret0, _ := ret[0].([]repository.Withdrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWithdrawals indicates an expected call of ListWithdrawals.
func (mr *MockBalanceRepositoryMockRecorder) ListWithdrawals(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWithdrawals", reflect.TypeOf((*MockBalanceRepository)(nil).ListWithdrawals), ctx, userID)
}

// Withdraw mocks base method.
func (m *MockBalanceRepository) Withdraw(ctx context.Context, userID int64, order string, sum float64, processedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Withdraw", ctx, userID, order, sum, processedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Withdraw indicates an expected call of Withdraw.
func (mr *MockBalanceRepositoryMockRecorder) Withdraw(ctx, userID, order, sum, processedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Withdraw", reflect.TypeOf((*MockBalanceRepository)(nil).Withdraw), ctx, userID, order, sum, processedAt)
}
